[package]
name = "const/ar-framework"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
future = "red-blox/future@1.0.1"
Signal = "sleitnick/signal@2.0.1"
ComplexRegions = "vocksel/complex-regions@0.1.2"
zoneplus = "bubshurb/zoneplus@1.1.1"
cmdr = "evaera/cmdr@1.12.0"
